name: build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          sudo apt update
          sudo apt install -y build-essential cmake curl libmpfr-dev libmpc-dev libgmp-dev e2fsprogs ninja-build qemu-system-gui qemu-system-x86 qemu-utils ccache rsync unzip texinfo libssl-dev
          git clone https://github.com/SerenityOS/serenity.git
          cd serenity
          Meta/serenity.sh run
          find . >files.txt

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          path: files.txt
